name: main
on:
  push:
  pull_request:

jobs:
  pre_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - uses: pre-commit/action@v3.0.1

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.4.30"

      - name: Set up Python
        run: uv python install 3.9

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run tests
        run: uv run pytest
